### ISSUE TITLE
Bor Rotar - popravljena koda

### ISSUE THREAD

**Issue by RotarB333** [jaanos/APPR-zagovori#30]
popravil sem napake, tako da bi zdaj moralo vse delovati.

zadnji commit:
RotarB333/APPR-2017-18@4ecad30d42abb362a345af30e4f90d9101dbab2a

**Comment by jaanos** [comment]
Bom dodal. Svetujem edino, da na koncu poročila pobrišeš Shiny, ki je še ostal iz vzorca.
