### ISSUE TITLE
Oddaja naloge (3. faza)

### ISSUE THREAD

**Issue by ajdastare** [jaanos/APPR-zagovori#31]
Pozdravljen!

Popravila sem projekt.rmd in ostale napake. Upam, da sedaj deluje.

Lp

**Comment by jaanos** [comment]
Poročilo prevede, tako da bom dodal povezavo. Bi pa opozoril na sledeče:
* V poročilo ti izpisuje opozorila - da se jih znebiš, v glavo blokov kode, kjer se pojavljajo, dodaj parameter `warning = FALSE` (lahko kar pri vseh blokh kode).
* V datoteki `podatki/0867806Ss.csv` se je pokvarilo kodiranje znakov. Svetujem, da podatke še enkrat pridobiš.
* Ne pozabi na svoje ime v glavi poročila.
