### ISSUE TITLE
3. faza

### ISSUE THREAD

**Issue by jakamun** [jaanos/APPR-zagovori#32]
Pozdravljeni!

Mislim, da bi poročilo moralo delovati. Vendar imam vprašanje, če se da zemljevid urediti tako da države za katere nimam podatkov obarvam na belo. Prav tako imam problem z funkcijo gsub, ki se jo uporabil v uvozu in sicer : st_na_1000_prebivalcev$Drzava <- gsub("Germany (until 1990 former territory of the FRG)", "Germany", st_na_1000_prebivalcev$Drzava). Ko jo poženem se ne spremeni nič, tak problem imam samo za  Nemčijo pri ostalih državah ta funkcija deluje.

Za odgovor se v naprej zahvaljujem.

Lep pozdrav

**Comment by jaanos** [comment]
Poročila ti trenutno ne prevede, ker imaš dva bloka kode z imenom `zemljevid`. Poskrb, da bo vsak blok kode imel svoje ime.

Če želiš države z manjkajočimi podatki pobarvati belo, lahko zemljevidu prišteješ še `scale_fill_continuous(na.value = "white")`. Zamenjava za Nemčijo pa ne deluje, ker so oklepaji posebni znaki v regularnih izrazih. Lažje bo, če zamenjuješ vse nize, ki se začnejo z `Germany`:
```R
starost$Drzava <- gsub("^Germany.*", "Germany", starost$Drzava)
```

**Comment by jakamun** [comment]
Sem popravil stvari, upam da sedaj deluje.

**Comment by jaanos** [comment]
Sedaj deluje, tako da bom dodal povezavo. Opažam sicer, da se v poročilo namesto grafov izpišejo ukazi `print` - te daj v ustrezne bloke kode, tako kot zadnja dva zemljevida. Pri teh se v poročilo izpiše opozorilo - da se ga znebiš, v glavo teh blokov kode dodaj še parameter `warning = FALSE`.
