### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by ztrojer** [jaanos/APPR-zagovori#35]
Pozdravljeni,

zaključil sem s tretjo fazo, zato vas prosim, če pogledate, če je vse OK. 
Zanima pa me samo, kako se v poročilu uredi lomljenje vrstice, torej ko nekaj naštevam, gre v naslednjo vrstico. 

Za odgovor se v naprej zahvaljujem.

Lep pozdrav

**Comment by jaanos** [comment]
Poročila pri meni ne prevede - programa v mapi `vizualizacija` imata namreč končnico `.R` (velika črka!), zato tako navajaj tudi, ko ju kličeš (nekateri sistemi so namreč občutljivi za velikost črk).

Če hočeš v (R)Markdownu narediti nov odstavek, pred njim pusti prazno vrstico. Enako velja tudi za sezname in druge elemente. Pred seznamom na koncu poročila torej dodaj še prazno vrstico.

**Comment by ztrojer** [comment]
Sem popravil,

Lep pozdrav
