### ISSUE TITLE
Posodobitev projekta

### ISSUE THREAD

**Issue by janrudof** [jaanos/APPR-zagovori#38]
Pozdravljeni,
pošiljam posodobljeno povezavo do mojega projekta:

janrudof/APPR-2017-18@ff4e44f

**Comment by jaanos** [comment]
V redu, bom posodobil.

Opažam le, da se pri prvem skupku grafov oznake na osi x prekrivajo. Ker navpičnega prostora ni veliko, bo najbrž najbolje, da te oznake nekoliko zmanjšaš - vsakemu grafu torej prištej npr. `theme(axis.text.x = element_text(size = 7))`.

**Comment by janrudof** [comment]
Nekako mi ni hotelo delati, da bi zmanjšal pisavo, tako da sem spremenil na malo drugačen način. 
Upam, da je sedaj prav. Prilagam povezavo do posodobitve:

janrudof/APPR-2017-18@bb2e819

Hvala za odkrito napako in popravek.
