### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by natasataskov** [jaanos/APPR-zagovori#42]
Pozdravljeni,
uredila sem projekt in vas prosim, da dodaste povezavo:
natasataskov/APPR-2017-18@ 9c38834 
na reprozitorij za zagovore, če vse vredu dela.

Hvala in lep pozdrav,
Nataša Taškov

**Comment by jaanos** [comment]
Poročila mi ne prevede - v njem namreč kličeš program `vizualizacija/zemljevid.R`, ki pa ga ni na repozitoriju. Si morda hotela uporabiti `vizualizacija/vizualizacija.r`, ali si pzabila vključiti prejšnji program v commit?

Svetoval bi še, da iz glave poročila odstraniš vrstico `runtime: shiny` - namesto *Run Document* se bo pojavil gumb *Knit*, s katerim poročilo prevedeš v obliko HTML. Opozoril bi še, da se je zemljevid na naslovu, ki ga imaš v `vizualizacija.r`, od lani spremenil, a imaš verjetno pri sebi še staro različico. Zato prosim v mapi nad tvojim projektom (lahko v RStudiu desno spodaj pri prikazu datotek klikneš na `..`) pojdi v mapo `zemljevidi` in tam pobriši mapo `fcd9a81eecc14d0af6e8c020f506fba4a9d65d58` (lahko pobrišeš kar vse mape, da ne boš pri sebi imela še kakšnih drugih starih zemljevidov). Potem se bo pri zagonu funkcije `uvozi.zemljevid` na novo pobral zemljevid, ki pa ima sedaj imena stolpcev z velikimi črkami. Namesto `continent`, `sovereignt` in `name_long` bo treba sedaj torej uporabiti `CONTINENT`, `SOVEREIGNT` in `NAME_LONG`.

**Comment by natasataskov** [comment]
Pozdravljeni,
sem popravila napake. Upam, da je vse vredu.
natasataskov/APPR-2017-18@  6f329d6

Lep pozdrav
Nataša Taškov

**Comment by jaanos** [comment]
Poročila še vedno ne prevede:
* Pri izrisovanju zemljevidov v poročilu uporabi `NAME_LONG` namesto `name_long`.
* Pri uvažanju zemljevida filtriraš po `NAME_LONG > -30`, kar seveda ni smiselno, zato je zemljevid prazen. Najbrž si hotela `long > -30`.

**Comment by natasataskov** [comment]
Pozdravljeni,
sem popravila. Upam, da sedaj vse dela, kot bi moralo.
natasataskov/APPR-2017-18@ 0d1a62a
