### ISSUE TITLE
posodobitev projekta

### ISSUE THREAD

**Issue by sarakovacic** [jaanos/APPR-zagovori#43]
sarakovacic/APPR-2017-18@ec3ae41502e3c4686e2aabebf0c0e76956899ba0

Prosim, da posodobite moj projekt.
Lep pozdrav,
Sara

**Comment by spelaognjanovic** [comment]
spelaognjanovic/APPR-2017-18@12519c5d2b79c5f1b87528fdf56e718cc67b772c

Prosim za posodobitev povezave.
Lep pozdrav,
Špela
