### ISSUE TITLE
Posodobitev

### ISSUE THREAD

**Issue by timotejvesel** [jaanos/APPR-zagovori#51]
Prosim, če lahko posodobite povezavo do mojega projekta:

timotejvesel/APPR-2017-18@d44d656 

Hvala.

**Comment by jaanos** [comment]
V redu, bom posodobil.

Opozoril bi le na to, da pri meni grafa `g4` ne prikaže, ker imaš šumnik v imenu bloka kode, kjer ga prikazuješ - če nadomestim `četrti` s `cetrti`, mi ga prikaže.
