### ISSUE TITLE
Dokončan projekt

### ISSUE THREAD

**Issue by jakamun** [jaanos/APPR-zagovori#53]
Jaz sem dokončal projekt zato prosim, če bi ga lahko pregledali in ga dodali na repozotorij.

Lep pozdrav

**Comment by jaanos** [comment]
V redu, bom dodal povezavo na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora. Če boš še kaj spreminjal, mi prosim javi, da posodobim povezavo.

Svetoval bi ti le, da v grafih v drugi Shiny aplikaciji podatke (število avtomobilov) deliš s 1000, da se izogneš eksponentni notaciji na osi y (seveda tudi ustrezno prilagodi oznako osi y). Poleg tega pride v zavihku *Goriva* pri nekaterih kombinacijah izbir do napake zaradi nezadostne raznolikosti podatkov. Tako svetujem, da preveriš, ali pride pri klicu funkcije `gam` do napake, ter v tem primeru ustrezno ukrepaš (npr. ne narišeš modela na graf, namesto napovedi pa izpišeš opozorilo):
```R
  mgam3 <- reactive({
    mgam <- tryCatch({
      gam(data = podatki3(), St_avtomobilov ~ s(Leto))
    }, error = function(e) { NULL })
  })
  
  output$gor <- renderPlot({
    h <- ggplot(data = podatki3(), aes(x=Leto, y=St_avtomobilov/1000)) + geom_point() +
      labs(title = input$d, x = "Leto", y = "Tisoči avtomobilov") +
      theme(plot.title = element_text(hjust = 0.5))
    if (! is.null(mgam3())) {
      h <- h + geom_smooth(method = "gam", formula = y ~ s(x))
    }
    h
  })
  
  output$gor1 <- renderTable({
    validate(need(! is.null(mgam3()), "Za napoved ni dovolj podatkov."))
    prihodnost <- data.frame(Leto=c(2018, 2019, 2020))
    napoved <- prihodnost %>% mutate(St_avtomobilov=predict(mgam3(), .))
    napoved$Leto <- as.integer(napoved$Leto)
    return(napoved)
  })
```
