### ISSUE TITLE
Dodajanje projekta

### ISSUE THREAD

**Issue by MancaStrgar** [jaanos/APPR-zagovori#55]
Pozdravljeni,
prosim, če mi lahko dodate projekt na repozitorij za zagovore.
Hvala!
Manca Strgar

**Comment by jaanos** [comment]
V redu, bom dodal povezavo, tako da se lahko z @alenFMF domeniš za termin zagovora. Če boš še kaj spreminjala, mi prosim javi, da posodobim povezavo.
